---
name: Build, test and push Docker Images

on:
    pull_request:
    push:
        branches:
            - main
    workflow_dispatch:

# https://docs.github.com/en/actions/using-jobs/using-concurrency
concurrency:
    # only cancel in-progress jobs or runs for the current workflow - matches against branch & tags
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    amd64-build:
        uses: ./.github/workflows/docker-build-test-upload.yml
        with:
            architecture: amd64
            runsOn: ubuntu-latest

    arm64-build:
        # This cost the runner minutes, so only run on PRs not from forks
        if: github.repository == 'aiidateam/aiida-core'
        uses: ./.github/workflows/docker-build-test-upload.yml
        with:
            architecture: arm64
            runsOn: buildjet-2vcpu-ubuntu-2204-arm

    amd64-push-ghcr:
        if: github.repository == 'aiidateam/aiida-core'
        uses: ./.github/workflows/docker-push.yml
        with:
            architecture: amd64
            registry: ghcr.io
        secrets:
            REGISTRY_USERNAME: ${{ github.actor }}
            REGISTRY_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        needs: [amd64-build]

    arm64-push-ghcr:
        if: github.repository == 'aiidateam/aiida-core'
        uses: ./.github/workflows/docker-push.yml
        with:
            architecture: arm64
            registry: ghcr.io
        secrets:
            REGISTRY_USERNAME: ${{ github.actor }}
            REGISTRY_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        needs: [arm64-build]

    merge-tags-ghcr:
        if: github.repository == 'aiidateam/aiida-core'
        uses: ./.github/workflows/docker-merge-tags.yml
        with:
            registry: ghcr.io
        secrets:
            REGISTRY_USERNAME: ${{ github.actor }}
            REGISTRY_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        needs: [amd64-push-ghcr, arm64-push-ghcr]

    amd64-push-dockerhub:
        if: github.repository == 'aiidateam/aiida-core' && (github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/v'))
        uses: ./.github/workflows/docker-push.yml
        with:
            architecture: amd64
            registry: docker.io
        secrets:
            REGISTRY_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
            REGISTRY_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
        needs: [amd64-build]

    arm64-push-dockerhub:
        if: github.repository == 'aiidateam/aiida-core' && (github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/v'))
        uses: ./.github/workflows/docker-push.yml
        with:
            architecture: arm64
            registry: docker.io
        secrets:
            REGISTRY_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
            REGISTRY_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
        needs: [arm64-build]

    merge-tags-dockerhub:
        if: github.repository == 'aiidateam/aiida-core' && (github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/v'))
        uses: ./.github/workflows/docker-merge-tags.yml
        with:
            registry: docker.io
        secrets:
            REGISTRY_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
            REGISTRY_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
        needs: [amd64-push-dockerhub, arm64-push-dockerhub]
